#!/bin/sh -e

# Author: Rick Balocca
# Date: 2007
# Description:

df=noninteractive
export DEBIAN_FRONTEND="$df"

echo "Vyatta full-upgrade status - Setting pin priority"
# add pin priority for vyatta
touch /etc/apt/preferences
sed -i '/BEGIN VYATTA ENTRY/,/END VYATTA ENTRY/{d}' /etc/apt/preferences
cat <<EOF >> /etc/apt/preferences
#Explanation: BEGIN VYATTA ENTRY
Package: *
Pin: release l=Vyatta
Pin-Priority: 1000
#Explanation: END VYATTA ENTRY
EOF

cd /tmp
echo "Vyatta full-upgrade status - Configuring unpacked packages"
dpkg --configure -a

echo "Vyatta full-upgrade status - Fixing any broken package dependencies"
apt-get -y -f install

checksum()
{(
	cd /opt/vyatta/bin
	md5sum	check-upgrade \
		download-only \
		_full-upgrade \
		full-upgrade \
		install-only \
		remove-packages \
		save-package-report \
		xes 2>/dev/null || true
)}

echo "Vyatta full-upgrade status - Resynchronizing package index files"
apt-get update
checksum >/tmp/full-upgrade.md5
echo "Vyatta full-upgrade status - Installing latest Vyatta-base package"
apt-get -y -f install vyatta-base
if ! (checksum | cmp - /tmp/full-upgrade.md5 >/dev/null)
then
	echo The vyatta-base package was not up to date.
	echo The latest one has been downloaded and
	echo full-upgrade is being restarted.
	rm -f /tmp/full-upgrade.md5
	exec /opt/vyatta/bin/full-upgrade $*
fi

rm -f /tmp/full-upgrade.md5
