#!/bin/sh -e

# Author: Rick Balocca
# Date: 2007
# Description:

nothing_installed()
{
	PATTERN='\<0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.'
	grep "$PATTERN" /tmp/install$$ && grep "$PATTERN" /tmp/upgrade$$
}

nothing_upgraded()
{
	PATTERN='\<0 upgraded, 0 newly installed'
	grep "$PATTERN" /tmp/install$$ && grep "$PATTERN" /tmp/upgrade$$
}

usage()
{
	echo "Usage: $0 -r -h -i"
	echo " Where"
	echo "  -r removes all vyatta packages before the install"
	echo "  -i runs interactively"
	echo "  -h shows this text"
}

df=noninteractive

while getopts rih opt
do
  case $opt in
  r)	remove_list=`dpkg -l|awk '{ print $2 }'|(grep 'vyatta' || true)`
        ;;
  i)	df=
	;;
  *)	usage
	exit
	;;
  esac
done

[ "$df" ] && export DEBIAN_FRONTEND="$df"

echo -n "Are you upgrading from a system console [Y/N]? "
read j
case "$j" in
y|Y|[yY][eE][sS] )
	;;
*)	echo "Then you are upgrading from a network connection."
	echo "Upgrade will result in interruption of system network"
	echo -n "connectivity to this session.  Do you wish to continue [Y/N]? "
	read j
	case "$j" in
	y|Y|[yY][eE][sS] )
		netupgrade=-y
		;;
	* )
		exit
		;;
	esac
	;;
esac

# Find all vyatta packages to remove
cd /tmp
dpkg --configure -a
apt-get -y -f install

apt-get update
md5sum /opt/vyatta/bin/full-upgrade 2>/dev/null >full-upgrade.md5 || true
apt-get -y -f install vyatta-base
if ! (md5sum /opt/vyatta/bin/full-upgrade | diff - full-upgrade.md5 >/dev/null)
then
	echo The full-upgrade script was not up to date.
	echo The latest one has been downloaded and
	echo full-upgrade is being restarted.
	rm -f full-upgrade.md5
	exec /opt/vyatta/bin/full-upgrade $*
fi

rm -f full-upgrade.md5

old_version=`grep '^Version' /opt/vyatta/etc/version|sed -e 's/.*[ 	]//'`
new_version=`apt-get --dry-run install vyatta-version|grep '^Inst'|sed -e 's/.*(//' -e 's/ .*//'`
case "$old_version" in 
[0-9]* )
	case "$new_version" in
	[0-9]* )
		;;
	* )
		echo ERROR: attempting to upgrade from supported to community
		exit 1
		;;
	esac
	;;
* )
	case "$new_version" in
	[0-9]* )
		remove_version_package=yes
		;;
	esac
	;;
esac

sed '3icase "$1" in upgrade) exit 0;; esac' -i /var/lib/dpkg/info/vyatta-quagga.prerm

apt-get $netupgrade -f autoremove #??

#[ "$remove_list" ] && dpkg -r --force-all $remove_list 2>/dev/null
[ "$remove_list" ] && dpkg -r --force-all $remove_list

apt-get -y -f install

# If we upgrading from 2.1 or earlier, we don't have a remove_list of installed packages,
# so generate it
if [ ! -f /opt/vyatta/etc/deb-versions.txt ] && which save-package-report >/dev/null
then
	save-package-report
fi

apt-get clean

(
	cd /opt/vyatta/etc
	mkdir /tmp/$$dir
	cp deb-versions.txt version build.txt /tmp/$$dir 2>/dev/null
)

set +e
apt-cache dumpavail|grep '^Package.*vyatta' |grep -v '^Package.*linux-header'| sed 's/Package:  *//'>/tmp/$$
set -e

install_list=`cat /tmp/$$`
####install_list="$install_list laptop-detect dhcp3-client tasksel ntpdate ed aptitude file"
echo Downloading updates.  This may take a few minutes...
apt-get -y -f --download-only install $install_list >/tmp/install$$
apt-get -y -f --download-only dist-upgrade >/tmp/upgrade$$

set +e

if nothing_installed
then
	echo
	echo System already upgraded to newest packages
	rm /tmp/install$$ /tmp/upgrade$$
	apt-get clean	# clean up the downloads in case we are close to full on root
	exit 0
fi

mv /tmp/$$dir/* /opt/vyatta/etc/.
rm -rf /tmp/$$dir

[ "$remove_version_package" ] && apt-get -y remove vyatta-version
apt-get -y install $install_list
apt-get -y -f install
apt-get -y install $install_list
apt-get -y dist-upgrade
apt-get -y -f install

##############################################################
which /opt/vyatta/bin/vyatta-show-version >/tmp/$$ && /opt/vyatta/bin/vyatta-show-version all>/tmp/$$

l=`grep '^Aii' /tmp/$$ | awk '{ print $2 }'`

if [ "$l" -a x"$netupgrade" = x ]
then
cat <<EOF
The Vyatta Upgrade procedure detected packages installed on
your system which are not required for this version of Vyatta
software.

This can occur because a package that Vyatta previously used
is no longer required OR because it is a package manually
added to your system by an administrator.

Unless you have a specific reason for keeping these
extra packages, Vyatta recommends that you allow the upgrade
procedure to delete them.  If you wish to keep them now,
but delete them later, you can do this using the CLI
"delete package" command.

The extra packages are listed below:

EOF

for i in $l
do
	echo $i
done

echo -n "Would you like to delete the extra packages listed above [Y/N]? "
read j
case "$j" in
y|Y|[yY][eE][sS] )
	apt-get --force-yes -y remove $l
	;;
*)
	echo These packages will be kept.
esac
fi

apt-get -y install `grep '^X' /tmp/$$ | awk '{ print $2 }'` \
		   `grep '^D' /tmp/$$ | awk '{ print $2 }'`

apt-get -y -f install

rm -f /tmp/$$
##############################################################

apt-get $netupgrade -f autoremove # ??
apt-get clean	# clean up the downloads in case we are close to full on root

# if we are upgrading from the net, don't bother asking the reboot question...
[ "$netupgrade" ] && reboot

echo You need to reboot the system to complete the upgrade
echo -n "Reboot now? "
read j
case "$j" in
y|Y|[yY][eE][sS] )
	reboot;;
esac
