#!/bin/sh

# Author: Rick Balocca
# Date: 2007
# Description:

cd /tmp
if [ "$1" ]
then
	/opt/vyatta/bin/_full-upgrade $*
else
	if ! mkdir full-upgrade
	then
		echo "full-upgrade can't acquire it's lock file (/tmp/full-upgrade)."
		echo "You may be attempting to run full-upgrade more than once simultaneously."
		exit 1
	fi
	hupfile=full-upgrade/nohup.out
	touch /root/full-upgrade.log
	nohup /opt/vyatta/bin/_full-upgrade $*>&$hupfile &
	tail -f /root/full-upgrade.log
fi
