#!/bin/sh

# Author: Rick Balocca
# Date: 2007
# Description:

stars="*******************************************************************************"

df=noninteractive
export DEBIAN_FRONTEND="$df"

# Find all vyatta packages to remove
cd /tmp
sed '3icase "$1" in upgrade) exit 0;; esac' -i /var/lib/dpkg/info/vyatta-quagga.prerm 2>/dev/null || true

echo -e "$stars\nVyatta full-upgrade status - Configuring unpacked packages"
dpkg --configure -a
echo -e "$stars\nVyatta full-upgrade status - Fixing any broken dependencies"
apt-get -f install
echo -e "$stars\nVyatta full-upgrade status - Removing no longer needed dependencies"
apt-get -f autoremove

install_list=`awk '{print $1}' /opt/vyatta/etc/deb-versions.txt|tr '\n' ' '`
if [ ! "$install_list" ]
then
	echo "Version package not installed correctly.  Exiting."
	exit 1
fi

echo -e "$stars\nVyatta full-upgrade status - Install retrieved packages"
apt-get -f install $install_list
echo -e "$stars\nVyatta full-upgrade status - Upgrade packages and handle dependencies"
apt-get dist-upgrade
echo -e "$stars\nVyatta full-upgrade status - Installed packages from new version"
echo -e "$stars\nVyatta full-upgrade status - Fixing any broken dependencies"
apt-get -f install
echo -e "$stars\nVyatta full-upgrade status - Removing no longer needed dependencies"
apt-get -f autoremove
echo -e "$stars\nVyatta full-upgrade status - Cleaning local repository of retrieved package files"
apt-get clean	# remove the downloads in case we are close to full on root

##### use UUID instead of device for grub
root_dev=$(mount | grep ' on / type ' | cut -f 1 -d ' '|sed 's,/dev/,,')

if grep ide=nodma /boot/grub/menu.lst /boot/grub/grub.cfg >&/dev/null
then
	grub_options=ide=nodma
fi

echo -e "$stars\nVyatta full-upgrade status - Setting up grub"
/opt/vyatta/sbin/vyatta-grub-setup "$root_dev" "$grub_options" || echo WARNING: grub not completely setup.
echo -e "$stars\nVyatta full-upgrade status - Completed grub setup"
