#!/usr/bin/expect -f

trap exit { SIGCHLD }

set timeout 99

log_user 0
log_file -a /root/full-upgrade.log

spawn $argv

for {} 1 {} {
	expect "*\\?" { send "Y\r" } timeout { send "Y\r" } eof { exit }
	expect_tty "*\\?" { send Y\r } timeout { send "Y\r" } eof { exit }
}
