#!/usr/bin/expect -f

trap exit { SIGCHLD }

# Default value
# set timeout 2

log_user 0
log_file -a /root/full-upgrade.log

spawn $argv

for {} 1 {} {
	expect -re ".*\\?" { send "Y\r\n" } eof { puts "BIT_IT_"; exit }
	expect_tty -re ".*\\?" { send "Y\r\n" } eof { puts "BIT_TTY_"; exit }
}
